name: example
description: "A new Flutter project."
publish_to: 'none'


environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.19.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  online_font:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true