name: online_font
description: A package to allow you to use online fonts in your flutter app.
version: 1.0.3+1
repository: https://github.com/huanghui1998hhh/online_font

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=3.19.2"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  crypto: ^3.0.6
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  mockito: ^5.0.0
  mustache_template: ^2.0.0
  path_provider_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.0.2
  test: ^1.25.7
